### ISSUE TITLE
Report inappropriate pastes

### ISSUE THREAD

**Issue by lus** [lus/pasty#12]
Maybe include a simple report system to give users the ability to report inappropriate pastes to the service hoster.

**Comment by kdev** [comment]
I think it would be enough to just have a simple button (with a flag) that sends a request with the paste id

**Comment by lus** [comment]
Jup, that is exactly what I had in mind.

**Comment by lus** [comment]
This feature is implemented and ready-to-use. https://pasty.lus.pm does not offer this feature yet as there are no report server implementations right now.
