### ISSUE TITLE
Api for Dev s

### ISSUE THREAD

**Issue by PascalMaximus** [lus/pasty#14]
Add a api for pasting to this

**Comment by kdev** [comment]
You could be smart an "reverse engineer" the api from here https://github.com/lus/pasty/blob/185f1511a64f7d452d95c8333b1e2280d483d786/web/assets/js/api.js

**Comment by MeerBiene** [comment]
POST "api/v1/pastes"
HEADERS "Content-Type": "application/json"
BODY
```json
{
"content": "example paste"
}
```
RETURNS
```json
{
"content": "example paste",
"deletionToken": "sdfsdfsdfsdf",
"id": "e87f7hewfun",
"suggestedSyntaxType": "js"
}
```

**Comment by lus** [comment]
Hey,

Yeah, as the others mentioned, there technically is a full API to interact with pasty, I was simply too lazy to document it.
I am currently working on the v2 API on branch `api-refactor` which will include a full documentation of all endpoints.
Until this point is reached, you could simply use @MeerBiene s kind summary of the paste creation endpoint.
If you have any further questions about the API, just comment on this issue, I (or any other helpful fellow) will explain everything to you ^^

**Comment by lus** [comment]
The API v2 is live on https://pasty.lus.pm now. Documentation can be found [here](https://github.com/lus/pasty/blob/develop/API.md). Feel free to ask further questions if they arise ^^.
