### ISSUE TITLE
Line number's don't line up with lines

### ISSUE THREAD

**Issue by Qwerty-Space** [lus/pasty#15]
Browser:  Firefox 89.0.2 
OS:  Linux

Pasty vs VS Code

![image](https://user-images.githubusercontent.com/6967592/125203493-79a4f380-e270-11eb-8d0f-9ab861411369.png) ![image](https://user-images.githubusercontent.com/6967592/125203543-ae18af80-e270-11eb-81f8-bf8ba9690ff9.png)

**Comment by lus** [comment]
Yeah, I already noticed that. Will be fixed with the next frontend update. Thank you.

**Comment by lus** [comment]
This got fixed with the last frontend PR.
