### ISSUE TITLE
Change Paste IDs to only use lowercase characters

### ISSUE THREAD

**Issue by TheRedshift** [lus/pasty#17]
Hi,

I was wondering how feasible/sensible it would be to change the ID generation to only use lowercase characters? Since the ID is the part that it's often easier to just type out at the destination, it would speed up that process, and if it causes a bottleneck due to the lower total possible IDs, the ID length can just be increased to compensate for anyone that has that issue.

To elaborate more, I frequently use my Pasty to share snippets between my work and personal computers, and the easiest way to do that is noting the generated ID on the computer I start on, and just appending that to the domain on the destination computer.

Not a massive issue at all, but if it's a small job to maybe add an environment variable to change ID generation (maybe even with the option to only have lowercase letters, or only numbers), it would be even more useful as a tool for me!

Thanks!

**Comment by lus** [comment]
Hello.
Thank you for your suggestion, I appreciate it!
Sorry for my delayed reply, I was kind of busy with the two just-merged PRs.
I think I will go with a simple environment variable containing all characters used for ID generation, which would be the most abstract and configurable way I can currently imagine. Feel free to bring up other ideas though if you want.

Do you currently have this problem with the public instance of pasty or are you hosting it yourself and are just looking for a configuration option?

**Comment by lus** [comment]
This feature is now pushed to branch `develop` and should be available using the Docker image `ghcr.io/lus/pasty:staging` in several minutes.
Feel free to ask further questions if some arise.

**Comment by TheRedshift** [comment]
Much appreciated, seems to be working perfectly for me, and specifically listing the characters to be used is a much cleaner solution than I was thinking of. Thanks again!
