### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by TheNomad11** [lus/pasty#2]
Looks promising, but could you please add installation instructions? Thanks

**Comment by lus** [comment]
Sure! I’ll add some in the following days!

**Comment by TheNomad11** [comment]
Cool! Thanks a lot!

**Comment by lus** [comment]
Sorry for the delay but I had some private stuff to manage.

FYI, I am currently doing some rework on branch `develop` as the codebase is kind of "legacy" (cannot call it really legacy yet lol).

This will include more detailed installation instructions, code cleanup, some driver rework (as it seems nobody really found out that the SQL driver actually does not work; there will only be postgres in the beginning, let's see if somebody misses MySQL/MariaDB) and API documentation.

If you have anything you want to suggest for that rework feel free to mention it here ^^

**Comment by lus** [comment]
Installation instructions are now included in the README on branch master and thus I will mark this issue as resolved.
If you have any further questions/suggestions/bugs feel free to open another one ^^
