### ISSUE TITLE
How to Get modification token? 

### ISSUE THREAD

**Issue by coolboy007** [lus/pasty#28]
I want to Edit my Filters file but when i click on save icon there is ask for the Modification token.. How can i get it?

**Comment by baalajimaestro** [comment]
You should have gotten it when you pasted, else if you have `PASTY_MODIFICATION_TOKENS=false` set, then you need the master token from `PASTY_MODIFICATION_TOKEN_MASTER`

**Comment by coolboy007** [comment]
but I'm using only telegram bot.

**Comment by lus** [comment]
Please head over to the developer of the Telegram bot you're using then. I don't offer support for any 3rd party products.

**Comment by coolboy007** [comment]
but I'm using @betterfilter telegram bot

**Comment by lus** [comment]
Then please ask him about how to get your modification token, this has nothing to do with pasty.
