### ISSUE TITLE
Send to pasty from CLI

### ISSUE THREAD

**Issue by Fastidious** [lus/pasty#34]
Is there a way to create a paste from CLI? If so, could I have an example on how to do it? Thanks!

**Comment by lus** [comment]
Hello.

Yes, you could actually create a shell alias for the following command:

```zsh
bash -c 'curl -Ls https://pasty.lus.pm/api/v2/pastes -d "{\"content\": \"$(echo $(</dev/stdin))\"}" | echo "https://pasty.lus.pm/$(echo $(</dev/stdin) | jq .id -r)"
```

If you called your alias `paste`, you can pipe in any data and receive a paste url like this:

```zsh
❯ echo "Hello, world" | paste
https://pasty.lus.pm/WX4A5F
```

Please note that you have to install `curl` and `jq` for that.

**Comment by Fastidious** [comment]
This worked lovely too, thank you very much! This is a good tidbit for a wiki page.
