### ISSUE TITLE
Disable deletion token

### ISSUE THREAD

**Issue by benyanke** [lus/pasty#5]
At times, I'd like to be able to deploy this in a way that doesn't provide a popup for a deletion token, just saving and providing a URL.

Would you be willing to allow a config option to disable the deletion token creation/popup?

**Comment by lus** [comment]
That sounds nice, I will implement it. Thank you!

**Comment by lus** [comment]
I pushed that feature to the `develop` branch to test it a few days until I'll fully release it. If you want to set it up for yourself, you may use the `ghcr.io/lus/pasty:staging` Docker image + tag ^^

Thanks for your suggestion. If you have any further problems/suggestions etc. feel free to open another issue!
