### ISSUE TITLE
Support for arm

### ISSUE THREAD

**Issue by batuhantrkgl** [lus/pasty#59]
" docker: no matching manifest for linux/arm/v7 in the manifest list entries. " 

it would be great if we can run it on arm devices.

**Comment by lus** [comment]
Hello! Thank you for your suggestion.
This issue only affects armv7 (32-bit), correct?
I will have a look into how well we can support 32-bit architectures, but it shouldn't be a big problem as far as I can see.

**Comment by batuhantrkgl** [comment]
Yeah! it only effects armv7 devices i guess.

Thanks for your hard-working too!

**Comment by lus** [comment]
Hello again.
I have added the `linux/arm/v7` architecture to the Docker workflow and the latest image indicates that it now includes a manifest entry for this arch.
I only did this for the `develop` branch for now, so you would need to pull `ghcr.io/lus/pasty:staging` or `ghcr.io/lus/pasty:2d54aba`.

Please give me a quick feedback if this fixes your issue :)

**Comment by batuhantrkgl** [comment]
Hey! it seems working great right now, thanks for your hard-work.

it loads normally, saves the page (a.k.a pasted content). 

Should i try anything other?

![image](https://github.com/lus/pasty/assets/76158371/d6502336-4b06-4504-bfea-ac87e720267f)
![image](https://github.com/lus/pasty/assets/76158371/0978dde5-bf5b-477d-baa3-25e0338c70de)

**Comment by lus** [comment]
Looks good, I will close this issue then.
If you encounter any further problems feel free to open another issue :)
